org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neoForge.parchment.minecraftVersion=1.21.10
neoForge.parchment.mappingsVersion=2025.10.12
minecraft_version=26.1

## Mod Properties
modid=classic_mobs
mod_version=1.0.0
neo_version=26.1.0.0-alpha.1+snapshot-1

jei_version=19.21.2.313
rei_version=16.0.729
emi_version=1.1.10
